import { Timestamp } from 'firebase/firestore';
import type { User, Pint } from '@/types';

export const DEMO_UID = 'demo';

export const DEMO_USER: User = {
  uid: DEMO_UID,
  displayName: 'Demo User',
  email: 'demo@guinness-passport.app',
  createdAt: Timestamp.fromMillis(new Date('2024-06-01').getTime()),
  totalPints: 12,
  avgRating: 4.25,
  homePub: 'The Long Hall',
  friendIds: [],
  badges: [],
  socialPints: 0,
};

export const DEMO_PINTS: Pint[] = [
  {
    id: 'demo-1',
    userId: DEMO_UID,
    pubName: 'The Long Hall',
    address: "51 South Great George's St, Dublin 2",
    placeId: 'demo-place-1',
    lat: 53.3435,
    lng: -6.2644,
    rating: 5,
    tags: ['Perfect Head', 'Creamy', 'Well-poured'],
    note: 'Arguably the best Guinness in Dublin. Worth every minute of the wait.',
    createdAt: Timestamp.fromMillis(new Date('2025-03-20').getTime()),
  },
  {
    id: 'demo-2',
    userId: DEMO_UID,
    pubName: "Mulligan's",
    address: '8 Poolbeg St, Dublin 2',
    placeId: 'demo-place-2',
    lat: 53.3463,
    lng: -6.2566,
    rating: 5,
    tags: ['Perfect Head', 'Smooth', 'Cold'],
    note: "Mulligan's never disappoints. Settled in two minutes flat.",
    createdAt: Timestamp.fromMillis(new Date('2025-03-14').getTime()),
  },
  {
    id: 'demo-3',
    userId: DEMO_UID,
    pubName: "Kehoe's",
    address: '9 South Anne St, Dublin 2',
    placeId: 'demo-place-3',
    lat: 53.3419,
    lng: -6.2607,
    rating: 4,
    tags: ['Creamy', 'Smooth'],
    note: 'Beautiful Victorian interior. Pint was excellent.',
    createdAt: Timestamp.fromMillis(new Date('2025-03-08').getTime()),
  },
  {
    id: 'demo-4',
    userId: DEMO_UID,
    pubName: 'Doheny & Nesbitt',
    address: '5 Lower Baggot St, Dublin 2',
    placeId: 'demo-place-4',
    lat: 53.3354,
    lng: -6.2519,
    rating: 4,
    tags: ['Well-poured', 'Cold'],
    note: '',
    createdAt: Timestamp.fromMillis(new Date('2025-02-28').getTime()),
  },
  {
    id: 'demo-5',
    userId: DEMO_UID,
    pubName: "Toner's",
    address: '139 Lower Baggot St, Dublin 2',
    placeId: 'demo-place-5',
    lat: 53.3347,
    lng: -6.2479,
    rating: 5,
    tags: ['Perfect Head', 'Creamy', 'Lively'],
    note: 'One of the oldest pubs in Dublin and the pint shows it. Perfect.',
    createdAt: Timestamp.fromMillis(new Date('2025-02-21').getTime()),
  },
  {
    id: 'demo-6',
    userId: DEMO_UID,
    pubName: 'The Brazen Head',
    address: '20 Lower Bridge St, Dublin 8',
    placeId: 'demo-place-6',
    lat: 53.3447,
    lng: -6.2752,
    rating: 3,
    tags: ['Flat', 'Lukewarm'],
    note: "A bit touristy — pint wasn't at its best tonight.",
    createdAt: Timestamp.fromMillis(new Date('2025-02-15').getTime()),
  },
  {
    id: 'demo-7',
    userId: DEMO_UID,
    pubName: 'The Long Hall',
    address: "51 South Great George's St, Dublin 2",
    placeId: 'demo-place-1',
    lat: 53.3435,
    lng: -6.2644,
    rating: 5,
    tags: ['Perfect Head', 'Well-poured', 'Creamy'],
    note: 'Back again. Still the best.',
    createdAt: Timestamp.fromMillis(new Date('2025-02-07').getTime()),
  },
  {
    id: 'demo-8',
    userId: DEMO_UID,
    pubName: 'The Black Harp',
    address: '5-6 Bachelor\'s Walk, Dublin 1',
    placeId: 'demo-place-7',
    lat: 53.3486,
    lng: -6.2633,
    rating: 4,
    tags: ['Cold', 'Smooth'],
    note: '',
    createdAt: Timestamp.fromMillis(new Date('2025-01-30').getTime()),
  },
  {
    id: 'demo-9',
    userId: DEMO_UID,
    pubName: "O'Donoghue's",
    address: '15 Merrion Row, Dublin 2',
    placeId: 'demo-place-8',
    lat: 53.3375,
    lng: -6.2508,
    rating: 4,
    tags: ['Creamy', 'Bitter'],
    note: 'Good music, great pint.',
    createdAt: Timestamp.fromMillis(new Date('2025-01-18').getTime()),
  },
  {
    id: 'demo-10',
    userId: DEMO_UID,
    pubName: "Mulligan's",
    address: '8 Poolbeg St, Dublin 2',
    placeId: 'demo-place-2',
    lat: 53.3463,
    lng: -6.2566,
    rating: 5,
    tags: ['Perfect Head', 'Creamy', 'Well-poured'],
    note: 'Christmas Eve pint. Tradition.',
    createdAt: Timestamp.fromMillis(new Date('2024-12-24').getTime()),
  },
  {
    id: 'demo-11',
    userId: DEMO_UID,
    pubName: 'The Stag\'s Head',
    address: '1 Dame Ct, Dublin 2',
    placeId: 'demo-place-9',
    lat: 53.3445,
    lng: -6.2638,
    rating: 4,
    tags: ['Smooth', 'Cold'],
    note: 'Stunning Victorian bar. Pint did it justice.',
    createdAt: Timestamp.fromMillis(new Date('2024-12-10').getTime()),
  },
  {
    id: 'demo-12',
    userId: DEMO_UID,
    pubName: 'The Gravity Bar',
    address: 'St. James\'s Gate, Dublin 8',
    placeId: 'demo-place-10',
    lat: 53.3418,
    lng: -6.2868,
    rating: 3,
    tags: ['Hazy', 'Cold'],
    note: 'The view is better than the pint, but worth it once.',
    createdAt: Timestamp.fromMillis(new Date('2024-11-22').getTime()),
  },
];
